server:
  port: 9000
  
spring:
  application:
    name: config-service
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/itsAhesan/ms
          default-label: main
          clone-on-start: true
